### PR TITLE
Next openbsd patches

### PR DESCRIPTION
**Pull request by espindola**

### CODE REVIEW

**Comment by alexpevzner** [comment]
Please, rename `refresh_ifaddrs` into `netif_refresh_ifaddrs` and add short comment before it, explaining what it does.

**Comment by alexpevzner** [comment]
There is one another thing: I need to obtain a name of a calling program, for logging/trace

To simplify porting, I've refactored it into the `os_progname()` function

**Comment by espindola** [comment]
I have updated the branch. I will take a looks at os_progname in another
pull request if you don't mind.

Cheers,
Rafael

**Comment by alexpevzner** [comment]
OK. I've merged and slightly updated code formatting

**Pull request merged**
