### PR TITLE
Simple changes for OpenBSD

### PR DESCRIPTION
**Pull request by espindola**
This pull request includes the simpler changes I had to make to build and run sane-airscan on OpenBSD.

There are a couple of more involved changes that I will send as a followup pull request.

### CODE REVIEW

**Comment by alexpevzner** [comment]
I'd prefer to put eventfd/pipe implementation under `#ifdef` -- on Linux eventfd has an obvious advantage of using less file descriptors.

You may also want to look to the FreeBSD port of the old (pre-WSD) version of the sane-airscan: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245540

It uses epoll-shim (https://github.com/jiixyj/epoll-shim), which provides eventfd emulation on a top of kqueue

Also, I'd prefer to use some existent errno code instead of `ERESTART`. The only requirement is that Avahi doesn't have any special logic for that code and unlikely to return it by itself. May be, `EBUSY`?

What are you going to do with airscan-netif.c? It uses rtnetlink socket to obtain notifications that something has changed with network interfaces; this is probably Linux-specific

**Comment by espindola** [comment]
> I'd prefer to put eventfd/pipe implementation under `#ifdef` -- on Linux eventfd has an obvious advantage of using less file descriptors.

Will do.

> You may also want to look to the FreeBSD port of the old (pre-WSD) version of the sane-airscan: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245540
> 
> It uses epoll-shim (https://github.com/jiixyj/epoll-shim), which provides eventfd emulation on a top of kqueue

That is an impressive hack. Since it is not in ports, I would be glad if I could avoid it.
 
> Also, I'd prefer to use some existent errno code instead of `ERESTART`. The only requirement is that Avahi doesn't have any special logic for that code and unlikely to return it by itself. May be, `EBUSY`?

Sure. I will update the poll request in a minute.
 
> What are you going to do with airscan-netif.c? It uses rtnetlink socket to obtain notifications that something has changed with network interfaces; this is probably Linux-specific

That is what I have for the second poll request. So far I have just disabled it. I am not sure what feature I am missing. I guess starting a scan program, turning on wifi and having the scanner show up?

**Comment by alexpevzner** [comment]
> That is an impressive hack. Since it is not in ports, I would be glad if I could avoid it.

OK

> That is what I have for the second poll request. So far I have just disabled it. I am not sure what feature I am missing. I guess starting a scan program, turning on wifi and having the scanner show up?

Yes, but it depends on a client too. If client periodically queries for update of a list of scanners, it will notice that scanner has appeared. Otherwise, it will show only scanners, discovered initially.

Unfortunately, SANE API misses normal PnP notification

**Comment by espindola** [comment]
> > That is an impressive hack. Since it is not in ports, I would be glad if I could avoid it.
> 
> OK

Thanks
 
> > That is what I have for the second poll request. So far I have just disabled it. I am not sure what feature I am missing. I guess starting a scan program, turning on wifi and having the scanner show up?
> 
> Yes, but it depends on a client too. If client periodically queries for update of a list of scanners, it will notice that scanner has appeared. Otherwise, it will show only scanners, discovered initially.

I am surprised that is not provided by sane itself, since more than one backend wants information about the network. In any case, I don't think it is a feature that most OpenBSD users would miss much. We like our config files :-)

I will send the second and last poll request once this is in.

**Comment by espindola** [comment]
So, is this updated version ok?

**Comment by alexpevzner** [comment]
Hi Rafael,

sorry for delayed response: I didn't notice that you've updated the patch.

I want to change few minor things:
1. Please, replace `#ifdef HAVE_EVENTFD` with `#ifdef __linux__` -- so build will be fully automatic, at least on Linux :-)
2. If you need to remove `cp -n` option, I want it to be replaced with some shell expression or something like this. With this option, `cp` doesn't override existent destination file. So if user builds by itself and then runs `make install`, his or her changes in the configuration file will not be lost

**Comment by espindola** [comment]
"Alexander Pevzner" <notifications@github.com> writes:

> Hi Rafael,
>
> sorry for delayed response: I didn't notice that you've updated the patch.

NP. Github notifications are not the best.

> I want to change few minor things:
>
> 1 Please, replace #ifdef HAVE_EVENTFD with #ifdef __linux__ -- so
> build will be fully automatic, at least on Linux :-)

Will do, but note that I also added

+#ifdef __linux__
+#define HAVE_EVENTFD
+#endif

So that, as far as I can tell, the build is still automatic.

> 2 If you need to remove cp -n option, I want it to be replaced with some shell expression or something like this. With this option, cp doesn't override existent
>  destination file. So if user builds by itself and then runs make install, his or her changes in the configuration file will not be lost

The closest single command I was able to find is "install -b". It still
replaces the existing file, but creates a backup.

I will go with

test -e foo || cp ...

for now. Let me now if you prefer "install -b"

Cheers,
Rafael

**Comment by espindola** [comment]
I have pushed a new version.

**Comment by alexpevzner** [comment]
> Will do, but note that I also added
>
>+#ifdef __linux__
>+#define HAVE_EVENTFD
>+#endif

Sorry, I didn't notice that. I think, if there will be more ports, I will eventually refactor it, but this is OK for now.

> test -e foo || cp ...

Yes, this is what I wanted. If user has edited configuration file, `make install` should not touch his or her changes

Thank you very much for your contribution! I hope you will port `airscan-netif.c` too, so OpenBSD variant will be as complete as Linux one

**Comment by alexpevzner** [comment]
Hi Rafael,

I just want to let you know, that your OpenBSD port has propagated up to the 0.99.20 stable release, which I've created a couple of minutes ago :-)

**Comment by espindola** [comment]
Awesome!

I have compiled and tested it, all good!

Cheers,
Rafael

**Pull request merged**
