### PR TITLE
Last patches for OpenBSD support

### PR DESCRIPTION
**Pull request by espindola**
The first two I am fairly confident about.

The last patch (IP_PKTINFO) is a hack. I am not sure what, at a high level, is being done, so I don't know what feature I am #ifdefing out.

### CODE REVIEW

**Comment by alexpevzner** [comment]
Hi,

full-functional replacement of Linux AF_NETLINK socket should not be very hard to implement.

Please, look here:

http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.sbin/ifstated/ifstated.c?annotate=1.64

Socket setup is at line 151 and messages handling at line 236.

That all looks quite similar to Linux, at conceptual level, though constants and structures are not the same.

I'd really prefer to have full implementation before it will be merged into my repository.

**Comment by espindola** [comment]
"Alexander Pevzner" <notifications@github.com> writes:

> Hi,
>
> full-functional replacement of Linux AF_NETLINK socket should not be very hard to implement.
>
> Please, look here:
>
> http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/usr.sbin/ifstated/ifstated.c?annotate=1.64
>
> Socket setup is at line 151 and messages handling at line 236.
>
> That all looks quite similar to Linux, at conceptual level, though constants and structures are not the same.
>
> I'd really prefer to have full implementation before it will be merged into my repository.

Will do. Sorry for the delay, I was busy with other "work".

Do you have a program you use to test netlink? I assume the test could be:

* Delete the scanner from the config file
* Turn off wifi
* Start scanning program
* Turn on wifi
* Check that scanner is detected and shows up

Correct?

Cheers,
Rafael

**Comment by alexpevzner** [comment]
I suggest you to enable console logging via configuration file, and uncomment `getchar` call in the test.c. You may also comment `scan_test`, so it will not annoy you with scanning attempts.

Then start this program. If you will play with `ifconfig up`/`ifconfig down` from another console, or add/delete IP address, it should be detected and appropriate messages should be printed to console

It would be nice if you will test adding/deletion of both IP4 and IP6 addresses

**Comment by espindola** [comment]
Abandoning this one for now. I will post a new series.

**Pull request closed without merging**
