### PR TITLE
Implement os_progname for OpenBSD

### PR DESCRIPTION
**Pull request by espindola**
I also removed the error in the #else, since the code is already setup
for os_progname returning NULL and just uses the name "unknown".

### CODE REVIEW

**Comment by alexpevzner** [comment]
I'd probably leave the `#error`, so when FreeBSD people will later port this code, the places where attention is required will be easily identified. You may leave a comment, though, that error here is not so critical

**Comment by espindola** [comment]
I pushed a new version with the `#error`.

**Comment by alexpevzner** [comment]
I have fixed Linux build. Please retest, that I didn't broke BSD build

**Comment by espindola** [comment]
Sorry about the breakage. I had no idea those headers were not available
on linux.

The fix is correct.

Thanks,
Rafael

**Comment by alexpevzner** [comment]
No problem at all. I also didn't know, that sys/sysctl.h is now deprecated on Linux

**Pull request merged**
