### PR TITLE
WIP: Add tiff decoder.

### PR DESCRIPTION
**Pull request by ThierryHFR**
I haven't done any tests, I don't have a device that supports tiff.
The build is ok.

### CODE REVIEW

**Comment by alexpevzner** [comment]
Hi @Ordissimo 

thank a lot for your contribution!

I've slightly tweaked your code. Do you have any objection, if I'll replace a long story about what SANE is in the beginning of the file with a short reference to the LICENSE file?

**Comment by alexpevzner** [comment]
Forgot to tell. Later I'll try to test your decoder. My device supports TIFF in WSD mode

**Comment by ThierryHFR** [comment]
No, I don't mind in aisane. But for integration into Sane, she'll have to be shaped like Sane.

⁣Télécharger BlueMail pour Android ​

Le 28 mars 2020 à 16:56, à 16:56, Alexander Pevzner <notifications@github.com> a écrit:

**Comment by alexpevzner** [comment]
OK. At this case, I will replace it for now, OK?

P.S. Till has thoroughly tested WSD and thinks that it is basically release-ready. So as soon as I'll finish with WS-Discovery, we will be able to push everything to sane-airscan

**Comment by ThierryHFR** [comment]
Le 2020-03-28 17:28, Alexander Pevzner a écrit :
> OK. At this case, I will replace it for now, OK?
Ok
> 
> P.S. Till has thoroughly tested WSD and thinks that it is basically
> release-ready. So as soon as I'll finish with WS-Discovery, we will be
> able to push everything to sane-airscan
Great!

**Pull request merged**
