### PR TITLE
Airscan bmp

### PR DESCRIPTION
**Pull request by ThierryHFR**
Implementation of the BMP codec.
I added the construction of a binary that allows me to test the decoders.

### CODE REVIEW

**Comment by alexpevzner** [comment]
Hi,

You are very fast! :-)

I have quickly reviewed you PR and will request some changes:
1. If you are doing memcpy() from some place in the buffer, please first check that this place exist (by checking actual data size). We should not trust any data coming from external sources
2. We should not assume that sizeof(int) == 4. There are special types for this purpose, such as int32_t, uint32_t and so on
3. We also should not assume that host has a little endian byte order. There are assortment of endian conversion functions, see man 3 endian
4. This is better to check overall header integrity before unpacking, check header signatures, if they are exist in this format and so on. If printer will send us junk, it is better to reject it with a reasonable diagnostics rather that try to unpack.

Please note, I'm not 100% sure if there BMP or DIB. As fas as I understand, BMP is the DIB with extra BMP header prepended. It's better to have some flexibility here (say, by #defining offsets or by conditional compilation) - so it will be easer to get it working on a real data.

**Comment by ThierryHFR** [comment]
I started from the idea that the Bitmap provided by the device, which uses a Windows protocol, was a Windows Bitmap.

I used Windows Bitmap decoding.
It is composed of :

1. BMP Header
2. BMP Info (DIB)
3. The data area.

I only support BGR or 1 color coded bitmaps.
It would be nice to have a color and black and white image to check that everything works well.

**Comment by ThierryHFR** [comment]
A problem remains in the BMP format (Bizzard choice for a scanner).
The beginning of the image is saved at the end of the file.
To have the imga in the right direction, you need :

1. Read the file line by line and add the lines from the end of the buffer.
2. Have the complete file read from the end to the beginning.

**Comment by alexpevzner** [comment]
Hi @Ordissimo 

My access to BMP-capable scanner is indirect. So I will be able to obtain real samples only a bit later, when I at leas partially implement the multi-format infrastructure,

In WSD protocol spec, the format we are speaking about, is called "dib". Which means that it may be DIB or may be BMP, and we will not know before we see the real sample. Fortunately, it is not a big change for us, the only difference is the BMP header.

Currently we can use ImageMagic to create BMP samples for testing purposes. I believe, that we are only interested in 1-bit B&W and 8-bit B&W and Color. BMP is the low-end hardware choice, unlikely that it will ever be used for more that 8 bits per pixel images.

For now we can assume that the entire BMP image is placed into the memory buffer. So there is no problem to read it from any direction. Yes, I understand, that these images are huge. But they are only required for devices that don't offer any other format but BMP. What I want to avoid is the need to have double buffers: one for received image and second for its unpacking.

When you extract various parameters from BMP header, you use memcpy. Here you implicitly assume that byte order of multi-byte integers is the same in BMP and on a computer. This assumption will be false if computer uses big-endiang byte order. Big endian computers are rare, but they exist (PowerPC, MIPS, some variants of ARM) Please, use explicit byte order conversion (see man 3 endian).

You also need to validate that every access to the BMP image buffer is within the actual buffer size (it is not impossible, that we will receive a correct header and truncated data). So either image_decoder_bmp_read_line() function should validate that it always reads image memory within the actual buffer boundaries, or image_decoder_bmp_begin() should validate decoded header parameters and return an error, if buffer is not large enough to keep the entire image. As for me, I'd prefer to check everything in the image_decoder_bmp_begin().

**Comment by ThierryHFR** [comment]
Thanks for the BMP image.
It's BMP V3 Windows encoded on 32 Bits (I had eliminated the 32 Bits).
I regret that the page is blank.
It's good that you added a test for the decoder.
It should be possible to test the rendering.
The BMP uses color palettes inserted in the file after the DIB header.
I can read the file, I would always have a greyscale rendering without the palette. 
It is used for 1, 4 and 8 bits.
For the 1Bits [0, 255]
For the 4 and 8 Bits, you really need to get it back to get the right rendering.

**Comment by alexpevzner** [comment]
I'v merged this PR manually. I don't want to merge test images.

For now I've dropped support for paletted images, as it is very unlikely that such images will be generated by scanner.

I also fixed orientation handling (top-to bottom vs bottom-to-top). BMP files use negative height to indicate top-to-bottom orientation, and I believe in most cases images will come from scanners in this orientation, because physically they are generated top-to-bottom, and this is very unlikely that scanner will waste its memory and CPU time to revert an image.

Thank you for your contribution!

**Pull request closed without merging**
