### PR TITLE
Comment out code depending on IP_PKTINFO

### PR DESCRIPTION
**Pull request by espindola**
This is a hack, but the last patch to get airscan working on OpenBSD
on my laptop. Maybe only because it has only one interface.

Looking at the openbsd source code, I don't see a way to get the
interface where a ipv4 packet was received.

I am not familiar with this code, but it looks like each resolver has
a different socket. Could we map directly from file descriptor to
resolver?

Signed-off-by: Rafael Ávila de Espíndola <rafael@espindo.la>

### CODE REVIEW

**Comment by alexpevzner** [comment]
> I am not familiar with this code, but it looks like each resolver has
a different socket.

No, it's a bit more complex. There are one unicast socket per resolver plus two sockets for multicast reception: one for IP4 and second for IP6.

You may look to Avahi source, how they do it (https://github.com/lathiat/avahi). This is in file avahi-core/socket.c. There is nothing deadly complex, but too much of code to directly quote it here.

**Comment by espindola** [comment]
Alexander Pevzner <notifications@github.com> writes:

>> I am not familiar with this code, but it looks like each resolver has
> a different socket.
>
> No, it's a bit more complex. There are one unicast socket per resolver plus two sockets for multicast reception: one for IP4 and second for IP6.
>
> You may look to Avahi source, how they do it (https://github.com/lathiat/avahi). This is in file avahi-core/socket.c. There is nothing deadly complex, but too much of code to directly quote it here.

IP_RECVIF seems to be the way to go. It is undocumented, I will try to
fix that too once I get aircan fully working.

What is a good way to test this? I can add a second interface with a
usb-ethernet adapter and use my phone tethering so that wifi is not on
the same network as the printer. Is that a reasonable way to do it?

Thanks,
Rafael

**Comment by alexpevzner** [comment]
Do you have WSD scanner near you?

**Comment by espindola** [comment]
Alexander Pevzner <notifications@github.com> writes:

> Do you have WSD scanner near you?

Yes, it is in my home office.

Cheers,
Rafael

**Pull request closed without merging**
