### PR TITLE
Next openbsd patches

### PR DESCRIPTION
**Pull request by espindola**
I finally found time to get back to this. I think I have AF_ROUTE working. I would just like to get a few simple patches in first.

### CODE REVIEW

**Comment by alexpevzner** [comment]
On Linux, I'd still prefer to parse RTNETLINK messages, to avoid `getifaddrs` and all subsequent logic roll, when it is not actually needed. When network interface goes up or down, Linux will send me 2-3 messages (one for address change, second for routing change and so on).

On BSD you may keep this logic simplified, it is up to you, but please make it compile-time conditional.

**Comment by espindola** [comment]
Alexander Pevzner <notifications@github.com> writes:

> On Linux, I'd still prefer to parse RTNETLINK messages, to avoid `getifaddrs` and all subsequent logic roll, when it is not actually needed. When network interface goes up or down, Linux will send me 2-3 messages (one for address change, second for routing change and so on).

OK. BTW, maybe I am missing a guarantee of this API, but what happens if
there are more messages than will fit the buffer? One of the messages
might be split at the end of the buffer, no?

Cheers,
Rafael

**Comment by espindola** [comment]
Alexander Pevzner <notifications@github.com> writes:

> On Linux, I'd still prefer to parse RTNETLINK messages, to avoid `getifaddrs` and all subsequent logic roll, when it is not actually needed. When network interface goes up or down, Linux will send me 2-3 messages (one for address change, second for routing change and so on).

I have pushed the series rebased and without the problematic patch.

I will try to update the remaining patches during the week.

Cheers,
Rafael

**Comment by alexpevzner** [comment]
> BTW, maybe I am missing a guarantee of this API, but what happens if there are more messages than will fit the buffer?

I don't know, really. Its not documented, and very hard to understand from kernel sources. But seems, nobody cares.

> One of the messages might be split at the end of the buffer, no?

No, it's message-oriented protocol, like UDP, unlike TCP. Message cannot be split, but can be truncated.

> I have pushed the series rebased and without the problematic patch.

OK. Thank you. I've merged.

**Pull request merged**
